# -*- coding: utf-8 -*-
"""função.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g66vMRggRRR5EwjCpZSUPCJ7-RRt-tUb
"""

def minha_funcao(valor1, valor2):
  return valor1 + valor2

resposta = minha_funcao(10, 10)

print("resposta", resposta)